const MINUTE_IN_MILLISECONDS = 60000;
const PollIntervals = {
  HALF_MINUTE_IN_MILLISECONDS: MINUTE_IN_MILLISECONDS / 2,
  THIRD_MINUTE_IN_MILLISECONDS: MINUTE_IN_MILLISECONDS / 3,
  QUARTER_MINUTE_IN_MILLISECONDS: MINUTE_IN_MILLISECONDS / 4,
};

export default PollIntervals;
