{{- include "shared-lib.serviceaccount" . }}
---
{{- include "shared-lib.frontend" . }}
---
{{- include "shared-lib.backend" . }}
---
{{- include "shared-lib.graphql" . }}
---
{{- include "shared-lib.ingress" . }}
