---
name: ci
run-name: ci ${{ github.event_name}} ${{ github.ref_name }} by ${{ github.actor }}
on:
  schedule:
    - cron: '20 11 * * *'
  pull_request:
  push:
    branches: ['develop']
  workflow_dispatch:
    inputs:
      env:
        type: environment
      ref:
        description: 'Branch, Tag, or SHA'
        required: true

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  REFERENCE: ${{ github.event.pull_request.head.sha || github.event.push.head_commit.id }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [frontend, backend, graphql]
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: gha
          aws-region: us-west-2
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.REFERENCE }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: latest
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: make build-${{ matrix.image }}
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
