---
name: deploy
run-name: ${{ github.event.inputs.env }} deploy ${{ github.ref_name }} ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
      ref:
        description: 'Branch, Tag, or Full SHA'
        required: true
        default: 'develop'

concurrency:
  group: ${{ github.event.inputs.env }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.event.inputs.env }}
    env:
      ENVIRONMENT: ${{ github.event.inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: gha
          aws-region: us-west-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask: 'true'
      - run: make deploy
      - run: make deploy-status
